version: '3.3'

services:
    #service 1: definition of mysql database
    db:
      image: mysql:8.0
      command: --init-connect='GRANT CREATE USER ON *.* TO ‘root’@‘%’;FLUSH PRIVILEGES;CREATE DATABASE photobook;'
      container_name: database   
      environment:
        - MYSQL_ROOT_PASSWORD=qwe123
        - MYSQL_ROOT_HOST=%
        - MYSQL_DATABASE=photobook
      ports:
        - "3306:3306"
      restart: always
      

    #service 2: definition of your spring-boot app 
    customerservice:                        #it is just a name, which will be used only in this file.
      image: telesina/photobook               #name of the image after dockerfile executes
      container_name: photobookcont  #name of the container created from docker image
      build:
        context: .                          #docker file path (. means root directory)
        dockerfile: Dockerfile              #docker file name
      ports:
        - "8080:8080"                       #docker containter port with your os port
      restart: always
        
      depends_on:                           #define dependencies of this app
        - db                                #dependency name (which is defined with this name 'db' in this file earlier)
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/photobook
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: qwe123